In [1]:
from pathlib import Path
import pandas as pd

# Raíz del proyecto: sube dos niveles desde notebooks/preprocesamiento
PROJECT_ROOT = Path.cwd().parents[1]

ruta_clima = PROJECT_ROOT / "data" / "raw" / "clima_mensual_caldas_2005_2025.csv"

clima = pd.read_csv(ruta_clima)
clima.head()

,municipio,date,temperature_2m,temperature_2m_min,temperature_2m_max,dewpoint_temperature_2m,total_precipitation_sum,volumetric_soil_water_layer_1,volumetric_soil_water_layer_2,surface_solar_radiation_downwards_sum,potential_evaporation_sum,total_evaporation_sum,surface_runoff_sum,sub_surface_runoff_sum,u_component_of_wind_10m,v_component_of_wind_10m,surface_pressure
0,Aguadas,2005-01-01,291.804963,288.014090,296.481504,289.330084,0.006429,0.431310,0.431033,1.622798e+07,-0.009457,-0.003028,0.000970,0.002272,-0.341390,0.039899,85026.066573
1,Anserma,2005-01-01,290.455535,287.462799,294.556604,288.783869,0.012678,0.416917,0.417416,1.459965e+07,-0.004430,-0.002734,0.003183,0.006314,0.254235,-0.151994,83380.962769
2,Aranzazu,2005-01-01,290.819072,286.843646,295.413461,288.652880,0.009284,0.429325,0.430741,1.589175e+07,-0.005409,-0.002874,0.001336,0.004796,-0.275160,0.031206,83999.319722
3,Belalcazar,2005-01-01,291.845785,288.910413,296.130977,290.458589,0.018061,0.422870,0.423448,1.419408e+07,-0.005602,-0.002861,0.007803,0.007237,0.306376,-0.160673,86439.542708
4,Chinchina,2005-01-01,290.599723,287.185265,294.854639,289.156133,0.025506,0.424694,0.425343,1.498360e+07,-0.005990,-0.003005,0.013007,0.009336,0.044786,-0.072563,84616.291360

In [2]:
# Tipificación y variables de fecha
clima["date"] = pd.to_datetime(clima["date"])

clima["anio"] = clima["date"].dt.year
clima["mes"] = clima["date"].dt.month

clima["municipio"] = clima["municipio"].astype("category")

print("Dimensiones:", clima.shape)
print("Municipios:", clima["municipio"].nunique())
print("Rango fechas:", clima["date"].min(), "→", clima["date"].max())

clima.head()

Dimensiones: (6777, 19)
Municipios: 27
Rango fechas: 2005-01-01 00:00:00 → 2025-11-01 00:00:00

,municipio,date,temperature_2m,temperature_2m_min,temperature_2m_max,dewpoint_temperature_2m,total_precipitation_sum,volumetric_soil_water_layer_1,volumetric_soil_water_layer_2,surface_solar_radiation_downwards_sum,potential_evaporation_sum,total_evaporation_sum,surface_runoff_sum,sub_surface_runoff_sum,u_component_of_wind_10m,v_component_of_wind_10m,surface_pressure,anio,mes
0,Aguadas,2005-01-01,291.804963,288.014090,296.481504,289.330084,0.006429,0.431310,0.431033,1.622798e+07,-0.009457,-0.003028,0.000970,0.002272,-0.341390,0.039899,85026.066573,2005,1
1,Anserma,2005-01-01,290.455535,287.462799,294.556604,288.783869,0.012678,0.416917,0.417416,1.459965e+07,-0.004430,-0.002734,0.003183,0.006314,0.254235,-0.151994,83380.962769,2005,1
2,Aranzazu,2005-01-01,290.819072,286.843646,295.413461,288.652880,0.009284,0.429325,0.430741,1.589175e+07,-0.005409,-0.002874,0.001336,0.004796,-0.275160,0.031206,83999.319722,2005,1
3,Belalcazar,2005-01-01,291.845785,288.910413,296.130977,290.458589,0.018061,0.422870,0.423448,1.419408e+07,-0.005602,-0.002861,0.007803,0.007237,0.306376,-0.160673,86439.542708,2005,1
4,Chinchina,2005-01-01,290.599723,287.185265,294.854639,289.156133,0.025506,0.424694,0.425343,1.498360e+07,-0.005990,-0.003005,0.013007,0.009336,0.044786,-0.072563,84616.291360,2005,1

Se cargó la base climática mensual extraída desde Google Earth Engine y se ajustaron los tipos de datos principales. La fecha se convirtió a formato datetime, se derivaron las columnas de año y mes, y el municipio se tipificó como categoría para facilitar el procesamiento posterior.

In [3]:
# Renombrar variables climáticas para facilitar interpretación
clima = clima.rename(columns={
    "temperature_2m": "temp_media_k",
    "temperature_2m_min": "temp_min_k",
    "temperature_2m_max": "temp_max_k",
    "dewpoint_temperature_2m": "temp_rocio_k",
    "total_precipitation_sum": "precip_m",
    "volumetric_soil_water_layer_1": "humedad_suelo_capa1",
    "volumetric_soil_water_layer_2": "humedad_suelo_capa2",
    "surface_solar_radiation_downwards_sum": "radiacion_solar_j_m2",
    "potential_evaporation_sum": "evap_potencial_m",
    "total_evaporation_sum": "evap_real_m",
    "surface_runoff_sum": "escorrentia_superficial_m",
    "sub_surface_runoff_sum": "escorrentia_subsuperficial_m",
    "u_component_of_wind_10m": "viento_u_ms",
    "v_component_of_wind_10m": "viento_v_ms",
    "surface_pressure": "presion_superficie_pa"
})

clima.head()

,municipio,date,temp_media_k,temp_min_k,temp_max_k,temp_rocio_k,precip_m,humedad_suelo_capa1,humedad_suelo_capa2,radiacion_solar_j_m2,evap_potencial_m,evap_real_m,escorrentia_superficial_m,escorrentia_subsuperficial_m,viento_u_ms,viento_v_ms,presion_superficie_pa,anio,mes
0,Aguadas,2005-01-01,291.804963,288.014090,296.481504,289.330084,0.006429,0.431310,0.431033,1.622798e+07,-0.009457,-0.003028,0.000970,0.002272,-0.341390,0.039899,85026.066573,2005,1
1,Anserma,2005-01-01,290.455535,287.462799,294.556604,288.783869,0.012678,0.416917,0.417416,1.459965e+07,-0.004430,-0.002734,0.003183,0.006314,0.254235,-0.151994,83380.962769,2005,1
2,Aranzazu,2005-01-01,290.819072,286.843646,295.413461,288.652880,0.009284,0.429325,0.430741,1.589175e+07,-0.005409,-0.002874,0.001336,0.004796,-0.275160,0.031206,83999.319722,2005,1
3,Belalcazar,2005-01-01,291.845785,288.910413,296.130977,290.458589,0.018061,0.422870,0.423448,1.419408e+07,-0.005602,-0.002861,0.007803,0.007237,0.306376,-0.160673,86439.542708,2005,1
4,Chinchina,2005-01-01,290.599723,287.185265,294.854639,289.156133,0.025506,0.424694,0.425343,1.498360e+07,-0.005990,-0.003005,0.013007,0.009336,0.044786,-0.072563,84616.291360,2005,1

Se renombraron las variables climáticas con nombres más interpretables, manteniendo referencia a sus unidades originales. Esto facilita la lectura del dataset y la posterior construcción de variables derivadas para el modelo.

In [4]:
# Conversión de unidades

# Temperatura: Kelvin a Celsius
clima["temp_media_c"] = clima["temp_media_k"] - 273.15
clima["temp_min_c"] = clima["temp_min_k"] - 273.15
clima["temp_max_c"] = clima["temp_max_k"] - 273.15
clima["temp_rocio_c"] = clima["temp_rocio_k"] - 273.15

# Precipitación: metros a mm
clima["precip_mm"] = clima["precip_m"] * 1000

# Evapotranspiración: metros a mm
clima["et_potencial_mm"] = clima["evap_potencial_m"] * 1000
clima["et_real_mm"] = clima["evap_real_m"] * 1000

# Escorrentía: metros a mm
clima["escorrentia_sup_mm"] = clima["escorrentia_superficial_m"] * 1000
clima["escorrentia_sub_mm"] = clima["escorrentia_subsuperficial_m"] * 1000

clima.head()

,municipio,date,temp_media_k,temp_min_k,temp_max_k,temp_rocio_k,precip_m,humedad_suelo_capa1,humedad_suelo_capa2,radiacion_solar_j_m2,...,mes,temp_media_c,temp_min_c,temp_max_c,temp_rocio_c,precip_mm,et_potencial_mm,et_real_mm,escorrentia_sup_mm,escorrentia_sub_mm
0,Aguadas,2005-01-01,291.804963,288.014090,296.481504,289.330084,0.006429,0.431310,0.431033,1.622798e+07,...,1,18.654963,14.864090,23.331504,16.180084,6.429084,-9.456613,-3.027861,0.969668,2.272478
1,Anserma,2005-01-01,290.455535,287.462799,294.556604,288.783869,0.012678,0.416917,0.417416,1.459965e+07,...,1,17.305535,14.312799,21.406604,15.633869,12.678457,-4.430061,-2.733630,3.182507,6.314069
2,Aranzazu,2005-01-01,290.819072,286.843646,295.413461,288.652880,0.009284,0.429325,0.430741,1.589175e+07,...,1,17.669072,13.693646,22.263461,15.502880,9.284075,-5.409199,-2.874198,1.336104,4.796001
3,Belalcazar,2005-01-01,291.845785,288.910413,296.130977,290.458589,0.018061,0.422870,0.423448,1.419408e+07,...,1,18.695785,15.760413,22.980977,17.308589,18.061409,-5.601514,-2.860718,7.802706,7.237414
4,Chinchina,2005-01-01,290.599723,287.185265,294.854639,289.156133,0.025506,0.424694,0.425343,1.498360e+07,...,1,17.449723,14.035265,21.704639,16.006133,25.506445,-5.989648,-3.004841,13.006616,9.335577

Se realizó la conversión de unidades de las variables climáticas. Las temperaturas fueron transformadas de Kelvin a grados Celsius, mientras que las variables de precipitación, evapotranspiración y escorrentía se convirtieron de metros a milímetros para asegurar  coherencia de las variables dentro del modelo.

#### vairables derivadas

In [5]:
clima_features = clima.copy()

# Balance hídrico: precipitación menos evapotranspiración potencial
clima_features["balance_hidrico_mm"] = (
    clima_features["precip_mm"] - clima_features["et_potencial_mm"]
)

# Amplitud térmica
clima_features["amplitud_termica_c"] = (
    clima_features["temp_max_c"] - clima_features["temp_min_c"]
)

# Velocidad del viento a partir de componentes U y V
clima_features["velocidad_viento_ms"] = (
    (clima_features["viento_u_ms"]**2 + clima_features["viento_v_ms"]**2) ** 0.5
)

clima_features[[
    "municipio", "date", "precip_mm", "et_potencial_mm",
    "balance_hidrico_mm", "temp_min_c", "temp_max_c",
    "amplitud_termica_c", "velocidad_viento_ms"
]].head()

,municipio,date,precip_mm,et_potencial_mm,balance_hidrico_mm,temp_min_c,temp_max_c,amplitud_termica_c,velocidad_viento_ms
0,Aguadas,2005-01-01,6.429084,-9.456613,15.885697,14.864090,23.331504,8.467414,0.343713
1,Anserma,2005-01-01,12.678457,-4.430061,17.108518,14.312799,21.406604,7.093805,0.296206
2,Aranzazu,2005-01-01,9.284075,-5.409199,14.693274,13.693646,22.263461,8.569816,0.276924
3,Belalcazar,2005-01-01,18.061409,-5.601514,23.662923,15.760413,22.980977,7.220563,0.345951
4,Chinchina,2005-01-01,25.506445,-5.989648,31.496093,14.035265,21.704639,7.669374,0.085271

Se construyeron variables derivadas para representar mejor las condiciones agroclimáticas. El balance hídrico aproxima condiciones de déficit o exceso de agua, la amplitud térmica resume la diferencia entre temperatura máxima y mínima, y la velocidad del viento integra los componentes horizontal y vertical del viento en una sola medida

In [6]:
# Variables derivadas adicionales

# Déficit hídrico (similar a balance pero enfocado en sequía)
clima_features["deficit_hidrico_mm"] = (
    clima_features["et_potencial_mm"] - clima_features["precip_mm"]
)

# Indicador de sequía (binario simple)
clima_features["estres_hidrico"] = (
    clima_features["balance_hidrico_mm"] < 0
).astype(int)

# Relación ET real vs potencial
clima_features["ratio_et"] = (
    clima_features["et_real_mm"] / (clima_features["et_potencial_mm"] + 1e-6)
)

# Humedad total del suelo
clima_features["humedad_suelo_total"] = (
    clima_features["humedad_suelo_capa1"] +
    clima_features["humedad_suelo_capa2"]
)

# Diferencia térmica con punto de rocío (proxy humedad atmosférica)
clima_features["dif_temp_rocio"] = (
    clima_features["temp_media_c"] - clima_features["temp_rocio_c"]
)

# Radiación (mantener pero con nombre más corto)
clima_features["radiacion"] = clima_features["radiacion_solar_j_m2"]

# Presión en kPa (más interpretable)
clima_features["presion_kpa"] = clima_features["presion_superficie_pa"] / 1000

clima_features.head()

,municipio,date,temp_media_k,temp_min_k,temp_max_k,temp_rocio_k,precip_m,humedad_suelo_capa1,humedad_suelo_capa2,radiacion_solar_j_m2,...,balance_hidrico_mm,amplitud_termica_c,velocidad_viento_ms,deficit_hidrico_mm,estres_hidrico,ratio_et,humedad_suelo_total,dif_temp_rocio,radiacion,presion_kpa
0,Aguadas,2005-01-01,291.804963,288.014090,296.481504,289.330084,0.006429,0.431310,0.431033,1.622798e+07,...,15.885697,8.467414,0.343713,-15.885697,0,0.320185,0.862344,2.474879,1.622798e+07,85.026067
1,Anserma,2005-01-01,290.455535,287.462799,294.556604,288.783869,0.012678,0.416917,0.417416,1.459965e+07,...,17.108518,7.093805,0.296206,-17.108518,0,0.617064,0.834332,1.671666,1.459965e+07,83.380963
2,Aranzazu,2005-01-01,290.819072,286.843646,295.413461,288.652880,0.009284,0.429325,0.430741,1.589175e+07,...,14.693274,8.569816,0.276924,-14.693274,0,0.531354,0.860066,2.166192,1.589175e+07,83.999320
3,Belalcazar,2005-01-01,291.845785,288.910413,296.130977,290.458589,0.018061,0.422870,0.423448,1.419408e+07,...,23.662923,7.220563,0.345951,-23.662923,0,0.510704,0.846317,1.387196,1.419408e+07,86.439543
4,Chinchina,2005-01-01,290.599723,287.185265,294.854639,289.156133,0.025506,0.424694,0.425343,1.498360e+07,...,31.496093,7.669374,0.085271,-31.496093,0,0.501673,0.850037,1.443590,1.498360e+07,84.616291

Se construyeron variables derivadas adicionales orientadas a capturar condiciones agroclimáticas relevantes. Estas incluyen indicadores de déficit hídrico, estrés por falta de agua, relación entre evapotranspiración real y potencial, humedad total del suelo y variables asociadas a la dinámica térmica y atmosférica.

In [7]:
clima_features = clima_features.sort_values(
    ["municipio", "date"]
).copy()

In [8]:
# Acumulados de lluvia
clima_features["precip_3m"] = (
    clima_features.groupby("municipio")["precip_mm"]
    .rolling(3).sum()
    .reset_index(level=0, drop=True)
)

clima_features["precip_6m"] = (
    clima_features.groupby("municipio")["precip_mm"]
    .rolling(6).sum()
    .reset_index(level=0, drop=True)
)


# Balance hídrico acumulado

clima_features["balance_3m"] = (
    clima_features.groupby("municipio")["balance_hidrico_mm"]
    .rolling(3).sum()
    .reset_index(level=0, drop=True)
)

clima_features["balance_6m"] = (
    clima_features.groupby("municipio")["balance_hidrico_mm"]
    .rolling(6).sum()
    .reset_index(level=0, drop=True)
)

/var/folders/wh/5gc4vknn1mz400bgbc5fd3080000gn/T/ipykernel_42860/1069443322.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  clima_features.groupby("municipio")["precip_mm"]
/var/folders/wh/5gc4vknn1mz400bgbc5fd3080000gn/T/ipykernel_42860/1069443322.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  clima_features.groupby("municipio")["precip_mm"]
/var/folders/wh/5gc4vknn1mz400bgbc5fd3080000gn/T/ipykernel_42860/1069443322.py:18: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  clima_features.groupby("municipio")["balance_hidrico_mm"]
/var/folders/wh/5gc4vknn1mz400bgbc5fd3080000gn/T/ipykernel_42860/1069443322.py:24: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  clima_features.groupby("municipio")["balance_hidrico_mm"]

Se incorporaron variables acumuladas y rezagos temporales con el fin de capturar efectos dinámicos del clima sobre el cultivo. Los acumulados permiten representar condiciones climáticas recientes, mientras que los rezagos incorporan memoria temporal,esto ya quelos impactos del clima no son inmediatos.

In [9]:
print("Dimensiones:", clima_features.shape)
print("Municipios:", clima_features["municipio"].nunique())
print("Rango:", clima_features["date"].min(), "→", clima_features["date"].max())
print("Nulos:\n", clima_features.isna().sum())

Dimensiones: (6777, 42)
Municipios: 27
Rango: 2005-01-01 00:00:00 → 2025-11-01 00:00:00
Nulos:
 municipio                         0
date                              0
temp_media_k                      0
temp_min_k                        0
temp_max_k                        0
temp_rocio_k                      0
precip_m                          0
humedad_suelo_capa1               0
humedad_suelo_capa2               0
radiacion_solar_j_m2              0
evap_potencial_m                  0
evap_real_m                       0
escorrentia_superficial_m         0
escorrentia_subsuperficial_m      0
viento_u_ms                       0
viento_v_ms                       0
presion_superficie_pa             0
anio                              0
mes                               0
temp_media_c                      0
temp_min_c                        0
temp_max_c                        0
temp_rocio_c                      0
precip_mm                         0
et_potencial_mm                   0
et_real_mm                        0
escorrentia_sup_mm                0
escorrentia_sub_mm                0
balance_hidrico_mm                0
amplitud_termica_c                0
velocidad_viento_ms               0
deficit_hidrico_mm                0
estres_hidrico                    0
ratio_et                          0
humedad_suelo_total               0
dif_temp_rocio                    0
radiacion                         0
presion_kpa                       0
precip_3m                        54
precip_6m                       135
balance_3m                       54
balance_6m                      135
dtype: int64

#### Lectura NDVI

In [10]:
ruta_ndvi = PROJECT_ROOT / "data" / "raw" / "ndvi_mensual_caldas_2005_2025.csv"

ndvi = pd.read_csv(ruta_ndvi)

# Limpiar columnas innecesarias
ndvi = ndvi.drop(columns=["system:index", ".geo"], errors="ignore")

# Tipificar
ndvi["date"] = pd.to_datetime(ndvi["date"])
ndvi["anio"] = ndvi["date"].dt.year
ndvi["mes"] = ndvi["date"].dt.month
ndvi["municipio"] = ndvi["municipio"].astype("category")

ndvi.head()

        date   municipio  ndvi_mean  anio  mes
0 2005-01-01     Aguadas   0.679795  2005    1
1 2005-01-01     Anserma   0.650176  2005    1
2 2005-01-01    Aranzazu   0.541243  2005    1
3 2005-01-01  Belalcazar   0.685661  2005    1
4 2005-01-01   Chinchina   0.700284  2005    1

In [11]:
print("Dimensiones:", ndvi.shape)
print("Municipios:", ndvi["municipio"].nunique())
print("Rango:", ndvi["date"].min(), "→", ndvi["date"].max())
print("Nulos:\n", ndvi.isna().sum())

Dimensiones: (6777, 5)
Municipios: 27
Rango: 2005-01-01 00:00:00 → 2025-11-01 00:00:00
Nulos:
 date         0
municipio    0
ndvi_mean    0
anio         0
mes          0
dtype: int64

#### MERGE

In [12]:
df_model = clima_features.merge(
    ndvi[["municipio", "date", "ndvi_mean"]],
    on=["municipio", "date"],
    how="inner"
)

df_model.head()

,municipio,date,temp_media_k,temp_min_k,temp_max_k,temp_rocio_k,precip_m,humedad_suelo_capa1,humedad_suelo_capa2,radiacion_solar_j_m2,...,ratio_et,humedad_suelo_total,dif_temp_rocio,radiacion,presion_kpa,precip_3m,precip_6m,balance_3m,balance_6m,ndvi_mean
0,Aguadas,2005-01-01,291.804963,288.014090,296.481504,289.330084,0.006429,0.431310,0.431033,1.622798e+07,...,0.320185,0.862344,2.474879,1.622798e+07,85.026067,NaN,NaN,NaN,NaN,0.679795
1,Aguadas,2005-02-01,293.009386,288.730749,298.161027,289.772418,0.004854,0.418266,0.417364,1.928667e+07,...,0.276744,0.835629,3.236968,1.928667e+07,84.962430,NaN,NaN,NaN,NaN,0.694975
2,Aguadas,2005-03-01,292.957695,288.081402,298.928790,289.781717,0.014913,0.432850,0.432259,2.185319e+07,...,0.291621,0.865109,3.175978,2.185319e+07,85.076309,26.196824,NaN,61.070316,NaN,0.735969
3,Aguadas,2005-04-01,292.149509,287.678161,297.544206,290.081049,0.010965,0.438857,0.441381,1.648955e+07,...,0.354994,0.880238,2.068461,1.648955e+07,85.031312,30.732862,NaN,64.729372,NaN,0.683911
4,Aguadas,2005-05-01,291.956984,287.639052,297.441098,289.748119,0.016490,0.439766,0.443595,1.725017e+07,...,0.367012,0.883361,2.208865,1.725017e+07,85.064573,42.368174,NaN,72.957013,NaN,0.755830

In [13]:
print("Dimensiones:", df_model.shape)
print("Municipios:", df_model["municipio"].nunique())
print("Rango fechas:", df_model["date"].min(), "→", df_model["date"].max())

print("Nulos:\n", df_model.isna().sum().sort_values(ascending=False))

Dimensiones: (6777, 43)
Municipios: 27
Rango fechas: 2005-01-01 00:00:00 → 2025-11-01 00:00:00
Nulos:
 balance_6m                      135
precip_6m                       135
balance_3m                       54
precip_3m                        54
municipio                         0
velocidad_viento_ms               0
et_potencial_mm                   0
et_real_mm                        0
escorrentia_sup_mm                0
escorrentia_sub_mm                0
balance_hidrico_mm                0
amplitud_termica_c                0
ratio_et                          0
deficit_hidrico_mm                0
estres_hidrico                    0
temp_rocio_c                      0
humedad_suelo_total               0
dif_temp_rocio                    0
radiacion                         0
presion_kpa                       0
precip_mm                         0
temp_max_c                        0
date                              0
evap_potencial_m                  0
temp_media_k                      0
temp_min_k                        0
temp_max_k                        0
temp_rocio_k                      0
precip_m                          0
humedad_suelo_capa1               0
humedad_suelo_capa2               0
radiacion_solar_j_m2              0
evap_real_m                       0
temp_min_c                        0
escorrentia_superficial_m         0
escorrentia_subsuperficial_m      0
viento_u_ms                       0
viento_v_ms                       0
presion_superficie_pa             0
anio                              0
mes                               0
temp_media_c                      0
ndvi_mean                         0
dtype: int64

In [14]:
df_model = df_model.dropna()
print("Dimensiones:", df_model.shape)

Dimensiones: (6642, 43)

#### cargamos producción

In [15]:
#ruta_prod = PROJECT_ROOT / "data" / "processed" / "produccion_caldas_2012_2024.csv"  

#produccion = pd.read_csv(ruta_prod)

#print("Dimensiones:", produccion.shape)
#produccion.head(10)

In [16]:
#ruta_prod = PROJECT_ROOT / "data" / "processed" / "produccion_caldas_municipal_2007-2024.csv"  

#produccion = pd.read_csv(ruta_prod)

#print("Dimensiones:", produccion.shape)
#produccion.head(10)

In [20]:
cols_drop = [
    "temp_media_k", "temp_min_k", "temp_max_k", "temp_rocio_k",
    "precip_m", "evap_potencial_m", "evap_real_m",
    "escorrentia_superficial_m", "escorrentia_subsuperficial_m",
    "presion_superficie_pa"
]

df_model = df_model.drop(columns=cols_drop, errors="ignore")

Se eliminaron algunas variables originales debido a que ya han sido transformadas a variables derivadas más interpretables para el análisis
las variables de temperatura en Kelvin fueron convertidas a grados Celsius
as variables expresadas en metros fueron transformadas a milímetros
la presión atmosférica fue convertida a kPa

Esta depuración evita duplicidad de información, reduce redundancia en el modelo y conserva las versiones más interpretables de cada variable

In [21]:
# Eliminar filas con nulos generados por variables acumuladas
df_model_limpio = df_model.dropna().copy()

print("Dimensiones antes:", df_model.shape)
print("Dimensiones después:", df_model_limpio.shape)

print("\nNulos restantes:")
print(df_model_limpio.isna().sum().sort_values(ascending=False).head(10))

Dimensiones antes: (6642, 33)
Dimensiones después: (6642, 33)

Nulos restantes:
municipio              0
escorrentia_sub_mm     0
balance_6m             0
balance_3m             0
precip_6m              0
precip_3m              0
presion_kpa            0
radiacion              0
dif_temp_rocio         0
humedad_suelo_total    0
dtype: int64

In [24]:
#df_model_limpio.head()

In [25]:
# Raíz del proyecto
PROJECT_ROOT = Path.cwd().parents[1]

# Ruta de salida
ruta_salida = PROJECT_ROOT / "data" / "processed" / "df_model_limpio_ndvi.csv"

# Exportar
df_model_limpio.to_csv(ruta_salida, index=False, encoding="utf-8-sig")

print("Archivo exportado en:")
print(ruta_salida)

Archivo exportado en:
/Users/daniel/Documents/GitHub/proyecto_aplicado_en_analitica_de_datos/data/processed/df_model_limpio_ndvi.csv